# Generated by Django 2.2.6 on 2020-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country name')),
                ('domain', models.CharField(max_length=50, verbose_name='Top Leve Domain')),
                ('alpha2Code', models.CharField(max_length=50, verbose_name='alpha2Code')),
                ('alpha3Code', models.CharField(max_length=50, verbose_name='alpha3Code')),
                ('callingCodes', models.CharField(max_length=50, verbose_name='callingCodes')),
                ('capital', models.CharField(max_length=50, verbose_name='capital')),
                ('altSpellings', models.CharField(max_length=50, verbose_name='altSpellings')),
                ('region', models.CharField(max_length=50, verbose_name='region')),
                ('subregion', models.CharField(max_length=50, verbose_name='subregion')),
                ('population', models.CharField(max_length=50, verbose_name='population')),
                ('latlng', models.CharField(max_length=50, verbose_name='latlng')),
                ('demonym', models.CharField(max_length=50, verbose_name='demonym')),
                ('area', models.CharField(max_length=50, verbose_name='area')),
                ('gini', models.CharField(max_length=50, verbose_name='gini')),
                ('timezones', models.CharField(max_length=50, verbose_name='timezones')),
                ('borders', models.CharField(max_length=50, verbose_name='borders')),
                ('nativeName', models.CharField(max_length=50, verbose_name='nativeName')),
                ('numericCode', models.CharField(max_length=50, verbose_name='numericCode')),
                ('currencies', models.CharField(max_length=50, verbose_name='currencies')),
                ('languages', models.CharField(max_length=50, verbose_name='languages')),
                ('translations', models.CharField(max_length=50, verbose_name='translations')),
                ('flag', models.CharField(max_length=50, verbose_name='flag')),
                ('regionalBlocs', models.CharField(max_length=50, verbose_name='regionalBlocs')),
                ('cioc', models.CharField(max_length=50, verbose_name='cioc')),
            ],
        ),
    ]
